### ISSUE TITLE
window install failed

### ISSUE THREAD

**Issue by miaotiao** [FriendsOfPHP/pickle#253]
```
PS C:\Users\mt\Downloads> php .\pickle.phar install redis
+---------------+---------------------------------------------------------------+
| php Path      | C:\Users\mt\soft\install\php-8.1.1-nts-Win32-vs16-x64\php.exe |
| php Version   | 8.1.1                                                         |
| Compiler      | vs16                                                          |
| Architecture  | x64                                                           |
| Thread safety | no                                                            |
| Extension dir | C:\Users\mt\soft\install\php-8.1.1-nts-Win32-vs16-x64\ext     |
| php.ini       | C:\Users\mt\soft\install\php-8.1.1-nts-Win32-vs16-x64\php.ini |
+---------------+---------------------------------------------------------------+
PHP Fatal error:  Uncaught Error: Call to undefined method Pickle\Package\PHP\Command\Install\Windows\Binary::setInput() in phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php:143
Stack trace:
#0 phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php(211): Pickle\Console\Command\InstallerCommand->binaryInstallWindows('redis', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Command/Command.php(298): Pickle\Console\Command\InstallerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Pickle\Console\Command\InstallerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#5 phar://C:/Users/mt/Downloads/pickle.phar/bin/pickle(38): Symfony\Component\Console\Application->run()
#6 C:\Users\mt\Downloads\pickle.phar(10): require('phar://C:/Users...')
#7 {main}
  thrown in phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php on line 143

Fatal error: Uncaught Error: Call to undefined method Pickle\Package\PHP\Command\Install\Windows\Binary::setInput() in phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php:143
Stack trace:
#0 phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php(211): Pickle\Console\Command\InstallerCommand->binaryInstallWindows('redis', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Command/Command.php(298): Pickle\Console\Command\InstallerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Pickle\Console\Command\InstallerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar://C:/Users/mt/Downloads/pickle.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))#5 phar://C:/Users/mt/Downloads/pickle.phar/bin/pickle(38): Symfony\Component\Console\Application->run()
#6 C:\Users\mt\Downloads\pickle.phar(10): require('phar://C:/Users...')
#7 {main}
  thrown in phar://C:/Users/mt/Downloads/pickle.phar/src/Console/Command/InstallerCommand.php on line 143
```

**Comment by MirazMac** [comment]
Facing the same issue

**Comment by xiaoliwang** [comment]
Facing the same issue

**Comment by xiaoliwang** [comment]
PR: https://github.com/FriendsOfPHP/pickle/pull/260
