### ISSUE TITLE
Pickle latest phar execution error

### ISSUE THREAD

**Issue by slushpuppy** [FriendsOfPHP/pickle#256]
Fatal error: Uncaught Error: Call to undefined function Pickle\Engine\exec() in phar:///usr/local/bin/pickle/src/Engine/PHP.php:279
Stack trace:
#0 phar:///usr/local/bin/pickle/src/Engine/PHP.php(82): Pickle\Engine\PHP->getFromConstants()
#1 phar:///usr/local/bin/pickle/src/Engine.php(51): Pickle\Engine\PHP->__construct()
#2 phar:///usr/local/bin/pickle/src/Package/Convey/Command/DefaultExecutor.php(55): Pickle\Engine::factory()
#3 phar:///usr/local/bin/pickle/src/Package/Convey/Command/SrcDir.php(49): Pickle\Package\Convey\Command\DefaultExecutor::factory()
#4 phar:///usr/local/bin/pickle/src/Package/Convey.php(63): Pickle\Package\Convey\Command\SrcDir->execute()
#5 phar:///usr/local/bin/pickle/src/Console/Helper/PackageHelper.php(119): Pickle\Package\Convey->deliver()
#6 phar:///usr/local/bin/pickle/src/Console/Command/InstallerCommand.php(217): Pickle\Console\Helper\PackageHelper->convey()
#7 phar:///usr/local/bin/pickle/vendor/symfony/console/Command/Command.php(298): Pickle\Console\Command\InstallerCommand->execute()
#8 phar:///usr/local/bin/pickle/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run()
#9 phar:///usr/local/bin/pickle/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#10 phar:///usr/local/bin/pickle/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#11 phar:///usr/local/bin/pickle/bin/pickle(38): Symfony\Component\Console\Application->run()
#12 /usr/local/bin/pickle(10): require('...')

php -v
PHP 8.1.6 (cli) (built: May 13 2022 22:28:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans

Debian 11, docker container

**Comment by slushpuppy** [comment]
running it as "php /usr/local/bin/pickle" works however, "/usr/local/bin/pickle" doesn't

**Comment by slushpuppy** [comment]
use a development version of php.ini that allows file functions to be used
